version: "3.8"

services:
  tritonserver:
    image: nvcr.io/nvidia/tritonserver:25.01-py3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "256m"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - .:/workspace
    command: tritonserver --model-repository=/workspace/model_repository
